; Webman 生产环境 PHP 配置
memory_limit = 256M
max_execution_time = 0
post_max_size = 100M
upload_max_filesize = 100M
date.timezone = Asia/Shanghai
; 错误处理
display_errors = Off
log_errors = On
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT