-- Normalize positive-only tinyint enum/flag columns to TINYINT UNSIGNED.
-- Keep the signed special case `goods.platform` because it uses -1 as a sentinel.

ALTER TABLE `ai_prompts`
  MODIFY COLUMN `is_favorite` TINYINT UNSIGNED NOT NULL DEFAULT 2;

ALTER TABLE `chat_participants`
  MODIFY COLUMN `is_pinned` TINYINT UNSIGNED NOT NULL DEFAULT 2;

ALTER TABLE `notification_task`
  MODIFY COLUMN `type` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'type: 1 info 2 success 3 warning 4 error',
  MODIFY COLUMN `level` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'level: 1 normal 2 urgent',
  MODIFY COLUMN `target_type` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'target type: 1 all 2 users 3 roles';

ALTER TABLE `notifications`
  MODIFY COLUMN `type` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'type: 1 normal 2 success 3 warning 4 error',
  MODIFY COLUMN `level` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'level: 1 normal 2 urgent',
  MODIFY COLUMN `is_read` TINYINT UNSIGNED NOT NULL DEFAULT 2 COMMENT '1 read 2 unread';

ALTER TABLE `operation_logs`
  MODIFY COLUMN `is_success` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1 success 2 fail';

ALTER TABLE `permission`
  MODIFY COLUMN `type` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'type: 1 dir 2 page 3 button',
  MODIFY COLUMN `keep_alive` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'keep-alive',
  MODIFY COLUMN `show_menu` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT 'show menu: 1 yes 2 no';

ALTER TABLE `tauri_version`
  MODIFY COLUMN `is_latest` TINYINT UNSIGNED NOT NULL DEFAULT 2,
  MODIFY COLUMN `force_update` TINYINT UNSIGNED NOT NULL DEFAULT 2;

ALTER TABLE `test`
  MODIFY COLUMN `type` TINYINT UNSIGNED NULL DEFAULT NULL,
  MODIFY COLUMN `sex` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY COLUMN `is_vip` TINYINT UNSIGNED NOT NULL DEFAULT 2,
  MODIFY COLUMN `is_hot` TINYINT UNSIGNED NOT NULL DEFAULT 2;

ALTER TABLE `user_profiles`
  MODIFY COLUMN `sex` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'sex: 0 unknown 1 male 2 female';

ALTER TABLE `users_login_log`
  MODIFY COLUMN `is_success` TINYINT UNSIGNED NOT NULL DEFAULT 2 COMMENT '1 success 2 fail';
